### ISSUE TITLE
可以修改一下筛选条件吗？

### ISSUE THREAD

**Issue by eternity1st** [surpassly/removefans#1]
可以把筛选条件由“发微博数小于3”改成“粉丝数小于3”吗？发微博数小于3的筛选条件还是无法清理部分僵尸粉。

**Comment by surpassly** [comment]
`Number(fans[i].querySelectorAll("span em.count")[1].innerText) < 3`
你在运行脚本的时候改下判断条件就行了，但是粉丝数小于3更容易是活粉。

**Comment by eternity1st** [comment]
好的，谢谢开发者
